"""Add users table

Revision ID: 0144eae5b750
Revises: 6218b941d920
Create Date: 2026-02-10 20:10:29.198145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0144eae5b750'
down_revision: Union[str, None] = '6218b941d920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table first
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # Delete existing tasks (acceptable for hackathon project)
    # This is necessary because we cannot convert VARCHAR to UUID with existing data
    op.execute('DELETE FROM tasks')

    # Now alter the column type to UUID
    op.alter_column('tasks', 'owner_user_id',
               existing_type=sa.VARCHAR(),
               type_=postgresql.UUID(as_uuid=True),
               existing_nullable=False,
               postgresql_using='owner_user_id::uuid')

    # Add foreign key constraint
    op.create_foreign_key('fk_tasks_owner_user_id_users', 'tasks', 'users', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_owner_user_id_users', 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'owner_user_id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
