openapi: 3.0.3
info:
  title: Task Management API
  description: RESTful API for managing user tasks with persistent storage in Neon PostgreSQL
  version: 1.0.0
  contact:
    name: Backend Core & Data Layer

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server (placeholder)

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for a user
      description: Retrieves all tasks belonging to the specified user. Returns empty array if user has no tasks.
      operationId: listTasks
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier (trusted input in this phase)
          schema:
            type: string
            example: "user123"
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                multiple_tasks:
                  summary: User with multiple tasks
                  value:
                    - id: 1
                      title: "Complete project documentation"
                      description: "Write comprehensive docs for the backend API"
                      completed: false
                      owner_user_id: "user123"
                      created_at: "2026-02-10T10:30:00Z"
                      updated_at: "2026-02-10T10:30:00Z"
                    - id: 2
                      title: "Review pull requests"
                      description: null
                      completed: true
                      owner_user_id: "user123"
                      created_at: "2026-02-10T09:15:00Z"
                      updated_at: "2026-02-10T11:45:00Z"
                empty_list:
                  summary: User with no tasks
                  value: []
        '503':
          description: Database connection error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new task
      description: Creates a new task for the specified user with the provided data
      operationId: createTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier (trusted input in this phase)
          schema:
            type: string
            example: "user123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            examples:
              with_description:
                summary: Task with description
                value:
                  title: "Complete project documentation"
                  description: "Write comprehensive docs for the backend API"
              without_description:
                summary: Task without description
                value:
                  title: "Review pull requests"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: "Complete project documentation"
                description: "Write comprehensive docs for the backend API"
                completed: false
                owner_user_id: "user123"
                created_at: "2026-02-10T10:30:00Z"
                updated_at: "2026-02-10T10:30:00Z"
        '400':
          description: Validation error (missing title, invalid data)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Field required: title"
                error_type: "ValidationError"
        '503':
          description: Database connection error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Retrieves a single task by ID if it belongs to the specified user
      operationId: getTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier (trusted input in this phase)
          schema:
            type: string
            example: "user123"
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: "Complete project documentation"
                description: "Write comprehensive docs for the backend API"
                completed: false
                owner_user_id: "user123"
                created_at: "2026-02-10T10:30:00Z"
                updated_at: "2026-02-10T10:30:00Z"
        '404':
          description: Task not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Task not found"
                error_type: "NotFoundError"
        '503':
          description: Database connection error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a task
      description: Updates title and description of an existing task if it belongs to the specified user
      operationId: updateTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier (trusted input in this phase)
          schema:
            type: string
            example: "user123"
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            example:
              title: "Complete project documentation (updated)"
              description: "Write comprehensive docs including API examples"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: "Complete project documentation (updated)"
                description: "Write comprehensive docs including API examples"
                completed: false
                owner_user_id: "user123"
                created_at: "2026-02-10T10:30:00Z"
                updated_at: "2026-02-10T12:15:00Z"
        '400':
          description: Validation error (missing title, invalid data)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Database connection error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a task
      description: Permanently removes a task if it belongs to the specified user
      operationId: deleteTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier (trusted input in this phase)
          schema:
            type: string
            example: "user123"
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Task deleted successfully (no content)
        '404':
          description: Task not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Database connection error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/{user_id}/tasks/{task_id}/complete:
    patch:
      summary: Mark a task as complete
      description: Sets the completed status of a task to true if it belongs to the specified user
      operationId: completeTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier (trusted input in this phase)
          schema:
            type: string
            example: "user123"
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Task marked as complete successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: "Complete project documentation"
                description: "Write comprehensive docs for the backend API"
                completed: true
                owner_user_id: "user123"
                created_at: "2026-02-10T10:30:00Z"
                updated_at: "2026-02-10T14:20:00Z"
        '404':
          description: Task not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Database connection error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      description: Complete task object with all fields
      required:
        - id
        - title
        - completed
        - owner_user_id
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique task identifier
          example: 1
        title:
          type: string
          maxLength: 200
          description: Task title
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          description: Optional detailed description
          example: "Write comprehensive docs for the backend API"
        completed:
          type: boolean
          description: Completion status
          example: false
        owner_user_id:
          type: string
          maxLength: 100
          description: User who owns this task
          example: "user123"
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
          example: "2026-02-10T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last modified
          example: "2026-02-10T10:30:00Z"

    TaskCreate:
      type: object
      description: Data required to create a new task
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 200
          description: Task title (required)
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          description: Optional detailed description
          example: "Write comprehensive docs for the backend API"

    TaskUpdate:
      type: object
      description: Data for updating an existing task
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 200
          description: Updated task title
          example: "Complete project documentation (updated)"
        description:
          type: string
          nullable: true
          description: Updated description
          example: "Write comprehensive docs including API examples"

    Error:
      type: object
      description: Error response format
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: "Task not found"
        error_type:
          type: string
          description: Error classification
          example: "NotFoundError"
          enum:
            - ValidationError
            - NotFoundError
            - DatabaseError

tags:
  - name: Tasks
    description: Task management operations
